
package lab6p2_diegorosales;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;


public class PanelPrincipal extends javax.swing.JFrame {
    int pos=0;
    /**
     * Creates new form PanelPrincipal
     */
    
    public PanelPrincipal() {
        
        
        initComponents();
        llenarPosiciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_CrearEquipos = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        button_crearequipo = new javax.swing.JButton();
        tf_pais = new javax.swing.JTextField();
        tf_nombreequipos = new javax.swing.JTextField();
        tf_ciudad = new javax.swing.JTextField();
        tf_estadio = new javax.swing.JTextField();
        crearequipos_goback = new javax.swing.JPanel();
        crearquipos_gobacktext = new javax.swing.JLabel();
        jd_CrearJugadores = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        button_crearjugadores = new javax.swing.JButton();
        tf_nombreJug = new javax.swing.JTextField();
        spinner_edad = new javax.swing.JSpinner();
        combobox_posicion = new javax.swing.JComboBox<>();
        crearjugadores_goback = new javax.swing.JPanel();
        crearjugadores_gobacktext = new javax.swing.JLabel();
        jd_Transferencias = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_jugadores = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tree_equipos = new javax.swing.JTree();
        button_transferir = new javax.swing.JButton();
        transferencias_goback = new javax.swing.JPanel();
        transferencias_gobacktext = new javax.swing.JLabel();
        popup_jugadores = new javax.swing.JPopupMenu();
        jmenu_modificar = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmenu_eliminar = new javax.swing.JMenu();
        jd_Modificar = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tf_nombre_modificar = new javax.swing.JTextField();
        spinner_edadmodificar = new javax.swing.JSpinner();
        button_modificar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        button_show_crearequipo = new javax.swing.JButton();
        button_show_crearjugadores = new javax.swing.JButton();
        button_show_transferencias = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_crearequipos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_crearjugadores = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menu_transferencias = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();

        jd_CrearEquipos.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Crear Equipos");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Pais");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Nombre");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Ciudad");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Estadio");

        button_crearequipo.setText("Crear");
        button_crearequipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_crearequipoMouseClicked(evt);
            }
        });
        button_crearequipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_crearequipoActionPerformed(evt);
            }
        });

        tf_nombreequipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreequiposActionPerformed(evt);
            }
        });

        crearequipos_goback.setBackground(new java.awt.Color(204, 204, 255));
        crearequipos_goback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearequipos_gobackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crearequipos_gobackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crearequipos_gobackMouseExited(evt);
            }
        });

        crearquipos_gobacktext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        crearquipos_gobacktext.setForeground(new java.awt.Color(0, 0, 0));
        crearquipos_gobacktext.setText("<------");

        javax.swing.GroupLayout crearequipos_gobackLayout = new javax.swing.GroupLayout(crearequipos_goback);
        crearequipos_goback.setLayout(crearequipos_gobackLayout);
        crearequipos_gobackLayout.setHorizontalGroup(
            crearequipos_gobackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearequipos_gobackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crearquipos_gobacktext, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );
        crearequipos_gobackLayout.setVerticalGroup(
            crearequipos_gobackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearequipos_gobackLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(crearquipos_gobacktext)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(crearequipos_goback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_pais, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_estadio))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_nombreequipos, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(button_crearequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3))
                    .addComponent(crearequipos_goback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_pais, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombreequipos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tf_ciudad))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_estadio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(button_crearequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout jd_CrearEquiposLayout = new javax.swing.GroupLayout(jd_CrearEquipos.getContentPane());
        jd_CrearEquipos.getContentPane().setLayout(jd_CrearEquiposLayout);
        jd_CrearEquiposLayout.setHorizontalGroup(
            jd_CrearEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_CrearEquiposLayout.setVerticalGroup(
            jd_CrearEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jd_CrearJugadores.setMaximumSize(new java.awt.Dimension(800, 600));
        jd_CrearJugadores.setMinimumSize(new java.awt.Dimension(800, 600));
        jd_CrearJugadores.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel4.setBackground(new java.awt.Color(102, 255, 102));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Crear Jugadores");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("Nombre");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("Edad");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("Posicion");

        button_crearjugadores.setText("Crear");
        button_crearjugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_crearjugadoresMouseClicked(evt);
            }
        });
        button_crearjugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_crearjugadoresActionPerformed(evt);
            }
        });

        tf_nombreJug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreJugActionPerformed(evt);
            }
        });

        spinner_edad.setModel(new javax.swing.SpinnerNumberModel(15, 15, 45, 1));

        combobox_posicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_posicionActionPerformed(evt);
            }
        });

        crearjugadores_goback.setBackground(new java.awt.Color(102, 255, 102));
        crearjugadores_goback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearjugadores_gobackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crearjugadores_gobackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crearjugadores_gobackMouseExited(evt);
            }
        });

        crearjugadores_gobacktext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        crearjugadores_gobacktext.setForeground(new java.awt.Color(0, 0, 0));
        crearjugadores_gobacktext.setText("<------");

        javax.swing.GroupLayout crearjugadores_gobackLayout = new javax.swing.GroupLayout(crearjugadores_goback);
        crearjugadores_goback.setLayout(crearjugadores_gobackLayout);
        crearjugadores_gobackLayout.setHorizontalGroup(
            crearjugadores_gobackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearjugadores_gobackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crearjugadores_gobacktext, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );
        crearjugadores_gobackLayout.setVerticalGroup(
            crearjugadores_gobackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearjugadores_gobackLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(crearjugadores_gobacktext)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(crearjugadores_goback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combobox_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(spinner_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(tf_nombreJug, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(button_crearjugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel8))
                    .addComponent(crearjugadores_goback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(tf_nombreJug, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spinner_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(combobox_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(button_crearjugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_CrearJugadoresLayout = new javax.swing.GroupLayout(jd_CrearJugadores.getContentPane());
        jd_CrearJugadores.getContentPane().setLayout(jd_CrearJugadoresLayout);
        jd_CrearJugadoresLayout.setHorizontalGroup(
            jd_CrearJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_CrearJugadoresLayout.setVerticalGroup(
            jd_CrearJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jd_Transferencias.setMaximumSize(new java.awt.Dimension(800, 600));
        jd_Transferencias.setMinimumSize(new java.awt.Dimension(800, 600));
        jd_Transferencias.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel5.setBackground(new java.awt.Color(255, 153, 102));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Transferencias");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Jugadores");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Equipos");

        jl_jugadores.setModel(new DefaultListModel());
        jl_jugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_jugadoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_jugadores);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Equipos");
        tree_equipos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(tree_equipos);

        button_transferir.setText("------->");
        button_transferir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_transferirMouseClicked(evt);
            }
        });
        button_transferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_transferirActionPerformed(evt);
            }
        });

        transferencias_goback.setBackground(new java.awt.Color(255, 153, 102));
        transferencias_goback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferencias_gobackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transferencias_gobackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transferencias_gobackMouseExited(evt);
            }
        });

        transferencias_gobacktext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        transferencias_gobacktext.setForeground(new java.awt.Color(0, 0, 0));
        transferencias_gobacktext.setText("<------");

        javax.swing.GroupLayout transferencias_gobackLayout = new javax.swing.GroupLayout(transferencias_goback);
        transferencias_goback.setLayout(transferencias_gobackLayout);
        transferencias_gobackLayout.setHorizontalGroup(
            transferencias_gobackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
            .addGroup(transferencias_gobackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(transferencias_gobackLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(transferencias_gobacktext, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addGap(7, 7, 7)))
        );
        transferencias_gobackLayout.setVerticalGroup(
            transferencias_gobackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(transferencias_gobackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(transferencias_gobackLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(transferencias_gobacktext)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(transferencias_goback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(143, 143, 143))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(button_transferir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel12))
                    .addComponent(transferencias_goback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(button_transferir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_TransferenciasLayout = new javax.swing.GroupLayout(jd_Transferencias.getContentPane());
        jd_Transferencias.getContentPane().setLayout(jd_TransferenciasLayout);
        jd_TransferenciasLayout.setHorizontalGroup(
            jd_TransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_TransferenciasLayout.setVerticalGroup(
            jd_TransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jmenu_modificar.setText("Modificar");
        jmenu_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmenu_modificarMouseClicked(evt);
            }
        });
        jmenu_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_modificarActionPerformed(evt);
            }
        });
        popup_jugadores.add(jmenu_modificar);
        popup_jugadores.add(jSeparator4);

        jmenu_eliminar.setText("Eliminar");
        popup_jugadores.add(jmenu_eliminar);

        jd_Modificar.setMaximumSize(new java.awt.Dimension(800, 600));
        jd_Modificar.setMinimumSize(new java.awt.Dimension(800, 600));
        jd_Modificar.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Modificar Jugador");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Nombre");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Edad");

        spinner_edadmodificar.setModel(new javax.swing.SpinnerNumberModel(15, 15, 45, 1));

        button_modificar.setText("Modificar");
        button_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_modificarMouseClicked(evt);
            }
        });
        button_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_modificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(tf_nombre_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(spinner_edadmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(button_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel15)
                .addGap(73, 73, 73)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_nombre_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(79, 79, 79)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spinner_edadmodificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(button_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jd_ModificarLayout = new javax.swing.GroupLayout(jd_Modificar.getContentPane());
        jd_Modificar.getContentPane().setLayout(jd_ModificarLayout);
        jd_ModificarLayout.setHorizontalGroup(
            jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_ModificarLayout.setVerticalGroup(
            jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gatito cortado.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bienvenido a Boroa League of Fantasy");

        jToolBar1.setBackground(new java.awt.Color(153, 255, 204));
        jToolBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setForeground(new java.awt.Color(0, 0, 0));
        jToolBar1.setRollover(true);

        button_show_crearequipo.setText("Crear Equipos");
        button_show_crearequipo.setFocusable(false);
        button_show_crearequipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_show_crearequipo.setMaximumSize(new java.awt.Dimension(104, 44));
        button_show_crearequipo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button_show_crearequipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_show_crearequipoMouseClicked(evt);
            }
        });
        button_show_crearequipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_show_crearequipoActionPerformed(evt);
            }
        });
        jToolBar1.add(button_show_crearequipo);

        button_show_crearjugadores.setText("Crear Jugadores");
        button_show_crearjugadores.setActionCommand("Crear Jugadores");
        button_show_crearjugadores.setFocusable(false);
        button_show_crearjugadores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_show_crearjugadores.setMaximumSize(new java.awt.Dimension(104, 44));
        button_show_crearjugadores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button_show_crearjugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_show_crearjugadoresActionPerformed(evt);
            }
        });
        jToolBar1.add(button_show_crearjugadores);

        button_show_transferencias.setText("Transferencias");
        button_show_transferencias.setFocusable(false);
        button_show_transferencias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_show_transferencias.setMaximumSize(new java.awt.Dimension(104, 44));
        button_show_transferencias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button_show_transferencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_show_transferenciasMouseClicked(evt);
            }
        });
        button_show_transferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_show_transferenciasActionPerformed(evt);
            }
        });
        jToolBar1.add(button_show_transferencias);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(83, 83, 83))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(206, 206, 206)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jMenu1.setText("Opciones");

        menu_crearequipos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_crearequipos.setText("Crear Equipos");
        menu_crearequipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_crearequiposActionPerformed(evt);
            }
        });
        jMenu1.add(menu_crearequipos);
        jMenu1.add(jSeparator1);

        menu_crearjugadores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_crearjugadores.setText("Crear Jugadores");
        menu_crearjugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_crearjugadoresActionPerformed(evt);
            }
        });
        jMenu1.add(menu_crearjugadores);
        jMenu1.add(jSeparator3);

        menu_transferencias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_transferencias.setText("Transferencias");
        menu_transferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_transferenciasActionPerformed(evt);
            }
        });
        jMenu1.add(menu_transferencias);
        jMenu1.add(jSeparator2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean validezNombre(String nombre){
        boolean flag=false;
        for (int i = 0; i < 10; i++) {
            if(nombre.contains(i+"")){
                flag=true;
            }
            else{
                
            }
        }
        if(flag==true){
            return false;
        }
        else{
            return true;
        }
       
    }
    private void llenarPosiciones(){
        DefaultComboBoxModel model = (DefaultComboBoxModel) combobox_posicion.getModel(); 
        model.addElement("Delantero");
        model.addElement("Defensa");
        model.addElement("Portero");
        combobox_posicion.setModel(model);
    }
    private void button_show_crearjugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_show_crearjugadoresActionPerformed
             this.setVisible(false);
        
        jd_CrearJugadores.setVisible(true);
        jd_CrearJugadores.pack();
        jd_CrearJugadores.setSize(800, 600);
    }//GEN-LAST:event_button_show_crearjugadoresActionPerformed

    private void button_show_crearequipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_show_crearequipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_show_crearequipoActionPerformed

    private void button_crearequipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_crearequipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_crearequipoActionPerformed

    private void button_crearjugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_crearjugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_crearjugadoresActionPerformed

    private void tf_nombreJugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreJugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreJugActionPerformed

    private void button_transferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_transferirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_transferirActionPerformed

    private void button_show_crearequipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_show_crearequipoMouseClicked
        this.setVisible(false);
        
        jd_CrearEquipos.setVisible(true);
        jd_CrearEquipos.pack();
        jd_CrearEquipos.setSize(800, 600);
    }//GEN-LAST:event_button_show_crearequipoMouseClicked

    private void crearequipos_gobackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearequipos_gobackMouseClicked
        jd_CrearEquipos.setVisible(false);
        this.setVisible(true);
        this.pack();
        this.setSize(800,600);
                
    }//GEN-LAST:event_crearequipos_gobackMouseClicked

    private void crearequipos_gobackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearequipos_gobackMouseEntered
        crearequipos_goback.setBackground(Color.red);
        crearquipos_gobacktext.setForeground(Color.white);
    }//GEN-LAST:event_crearequipos_gobackMouseEntered

    private void crearequipos_gobackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearequipos_gobackMouseExited
        crearequipos_goback.setBackground(new Color(204,204,255));
        crearquipos_gobacktext.setForeground(Color.black);
    }//GEN-LAST:event_crearequipos_gobackMouseExited

    private void crearjugadores_gobackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearjugadores_gobackMouseClicked
             jd_CrearJugadores.setVisible(false);
        this.setVisible(true);
        this.pack();
        this.setSize(800,600);
            
    }//GEN-LAST:event_crearjugadores_gobackMouseClicked

    private void crearjugadores_gobackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearjugadores_gobackMouseEntered
        crearjugadores_goback.setBackground(Color.red);
        crearjugadores_gobacktext.setForeground(Color.white);
    }//GEN-LAST:event_crearjugadores_gobackMouseEntered

    private void crearjugadores_gobackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearjugadores_gobackMouseExited
        crearjugadores_goback.setBackground(new Color(102,255,102));
        crearjugadores_gobacktext.setForeground(Color.black);
    }//GEN-LAST:event_crearjugadores_gobackMouseExited

    private void transferencias_gobackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferencias_gobackMouseClicked
               jd_Transferencias.setVisible(false);
        this.setVisible(true);
        this.pack();
        this.setSize(800,600);
            
    }//GEN-LAST:event_transferencias_gobackMouseClicked

    private void transferencias_gobackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferencias_gobackMouseEntered
       transferencias_goback.setBackground(Color.red);
        transferencias_gobacktext.setForeground(Color.white);
    }//GEN-LAST:event_transferencias_gobackMouseEntered

    private void transferencias_gobackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferencias_gobackMouseExited
        transferencias_goback.setBackground(new Color(255,153,102));
        transferencias_gobacktext.setForeground(Color.black);
    }//GEN-LAST:event_transferencias_gobackMouseExited

    private void button_show_transferenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_show_transferenciasMouseClicked
        this.setVisible(false);
        
        jd_Transferencias.setVisible(true);
        jd_Transferencias.pack();
        jd_Transferencias.setSize(800, 600);
        
    }//GEN-LAST:event_button_show_transferenciasMouseClicked

    private void jl_jugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_jugadoresMouseClicked
        if(jl_jugadores.getSelectedIndex()>=0){
            if(evt.getButton()==3){
                popup_jugadores.show(jl_jugadores, evt.getX(), evt.getY());
                pos = jl_jugadores.getSelectedIndex();
            }
        }
    }//GEN-LAST:event_jl_jugadoresMouseClicked

    private void combobox_posicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_posicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_posicionActionPerformed

    private void tf_nombreequiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreequiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreequiposActionPerformed

    
    private void button_transferirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_transferirMouseClicked
        DefaultTreeModel treemodel = (DefaultTreeModel) tree_equipos.getModel();
        DefaultListModel listmodel = (DefaultListModel) jl_jugadores.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) treemodel.getRoot();
        
            DefaultMutableTreeNode posicion;
            DefaultMutableTreeNode jugador;
        int jseleccionado = jl_jugadores.getSelectedIndex();
       
        
    }//GEN-LAST:event_button_transferirMouseClicked

    private void button_crearequipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_crearequipoMouseClicked
        if(tf_pais.getText().isEmpty() || tf_nombreequipos.getText().isEmpty() || tf_ciudad.getText().isEmpty() || tf_estadio.getText().isEmpty()){
            JOptionPane.showMessageDialog(jd_CrearEquipos, "Tienes que llenar todos los campos para crear un equipo");
        }
        else{
            Equipo e = new Equipo();
            e.setNombre(tf_nombreequipos.getText());
            e.setPais(tf_pais.getText());
            e.setCiudad(tf_ciudad.getText());
            e.setEstadio(tf_estadio.getText());
            
            
            DefaultTreeModel treemodel = (DefaultTreeModel) tree_equipos.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) treemodel.getRoot();
            
             DefaultMutableTreeNode nodoEquipo;
            nodoEquipo = new DefaultMutableTreeNode(new Equipo(tf_pais.getText(),tf_nombreequipos.getText(),tf_ciudad.getText(),tf_estadio.getText()));
            
            
            boolean c = false;
            int var = 0;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if(raiz.getChildAt(i).toString().equals(tf_pais.getText())){
                    ((DefaultMutableTreeNode)raiz.getChildAt(i)).add(nodoEquipo);
                    raiz.add(((DefaultMutableTreeNode)raiz.getChildAt(i)));
                    c=true;
                    
                }
            }
            if(c==false){
            DefaultMutableTreeNode nodoPais;
            nodoPais = new DefaultMutableTreeNode(tf_pais.getText());
            nodoPais.add(nodoEquipo);
            raiz.add(nodoPais);
            treemodel.reload();
            }
            else{
                treemodel.reload();
            }
            tf_ciudad.setText("");
            tf_estadio.setText("");
            tf_nombreequipos.setText("");
            tf_pais.setText("");
                   
                    
             
        }
    }//GEN-LAST:event_button_crearequipoMouseClicked

    private void button_crearjugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_crearjugadoresMouseClicked
        if(tf_nombreJug.getText().isEmpty()){
            JOptionPane.showMessageDialog(jd_CrearJugadores, "Tienes que llenar todos los campos para crear un Jugador");
        }
        else{
            Jugador j = new Jugador();
            
            
            j.setNombre(tf_nombreJug.getText());
            j.setEdad((Integer)spinner_edad.getValue());
            j.setPosicion(combobox_posicion.getSelectedItem().toString());
            DefaultListModel m = (DefaultListModel) jl_jugadores.getModel();
            m.addElement(j);
            jl_jugadores.removeAll();
            jl_jugadores.setModel(m);
            
            tf_nombreJug.setText("");
            
            
        }
    }//GEN-LAST:event_button_crearjugadoresMouseClicked

    private void menu_crearequiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_crearequiposActionPerformed
          this.setVisible(false);
        
        jd_CrearEquipos.setVisible(true);
        jd_CrearEquipos.pack();
        jd_CrearEquipos.setSize(800, 600);
    }//GEN-LAST:event_menu_crearequiposActionPerformed

    private void menu_crearjugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_crearjugadoresActionPerformed
            this.setVisible(false);
        
        jd_CrearJugadores.setVisible(true);
        jd_CrearJugadores.pack();
        jd_CrearJugadores.setSize(800, 600);
    }//GEN-LAST:event_menu_crearjugadoresActionPerformed

    private void button_show_transferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_show_transferenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_show_transferenciasActionPerformed

    private void menu_transferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_transferenciasActionPerformed
       this.setVisible(false);
        
        jd_Transferencias.setVisible(true);
        jd_Transferencias.pack();
        jd_Transferencias.setSize(800, 600);
       
    }//GEN-LAST:event_menu_transferenciasActionPerformed

    private void button_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_modificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_modificarActionPerformed

    private void button_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_modificarMouseClicked
        boolean ver = validezNombre(tf_nombre_modificar.getText());
        if(ver==true){
            DefaultListModel l = (DefaultListModel) jl_jugadores.getModel();
            ((Jugador)l.get(pos)).setNombre(tf_nombre_modificar.getText());
            ((Jugador)l.get(pos)).setEdad((Integer)spinner_edadmodificar.getValue());
            jl_jugadores.removeAll();
            jl_jugadores.setModel(l);
            jd_Modificar.setVisible(false);
            jd_Transferencias.setVisible(true);
            jd_Transferencias.pack();
            jd_Transferencias.setSize(800, 600);
       
        }
        else{
            JOptionPane.showMessageDialog(jd_Modificar, "Error, el nomrbe contiene un numero");
        }
    }//GEN-LAST:event_button_modificarMouseClicked

    private void jmenu_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_modificarActionPerformed
        
    }//GEN-LAST:event_jmenu_modificarActionPerformed

    private void jmenu_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenu_modificarMouseClicked
        this.setVisible(false);
        
        DefaultListModel l = (DefaultListModel) jl_jugadores.getModel();
        tf_nombre_modificar.setText(((Jugador)l.get(pos)).getNombre());
        spinner_edadmodificar.setValue(((Jugador)l.get(pos)).getEdad());
        jd_Modificar.setVisible(true);
        jd_Modificar.pack();
        jd_Modificar.setSize(800, 600);
    }//GEN-LAST:event_jmenu_modificarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_crearequipo;
    private javax.swing.JButton button_crearjugadores;
    private javax.swing.JButton button_modificar;
    private javax.swing.JButton button_show_crearequipo;
    private javax.swing.JButton button_show_crearjugadores;
    private javax.swing.JButton button_show_transferencias;
    private javax.swing.JButton button_transferir;
    private javax.swing.JComboBox<String> combobox_posicion;
    private javax.swing.JPanel crearequipos_goback;
    private javax.swing.JPanel crearequipos_goback1;
    private javax.swing.JPanel crearequipos_goback2;
    private javax.swing.JPanel crearjugadores_goback;
    private javax.swing.JLabel crearjugadores_gobacktext;
    private javax.swing.JLabel crearquipos_gobacktext;
    private javax.swing.JLabel crearquipos_gobacktext1;
    private javax.swing.JLabel crearquipos_gobacktext2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDialog jd_CrearEquipos;
    private javax.swing.JDialog jd_CrearJugadores;
    private javax.swing.JDialog jd_Modificar;
    private javax.swing.JDialog jd_Transferencias;
    private javax.swing.JList<String> jl_jugadores;
    private javax.swing.JMenu jmenu_eliminar;
    private javax.swing.JMenu jmenu_modificar;
    private javax.swing.JMenuItem menu_crearequipos;
    private javax.swing.JMenuItem menu_crearjugadores;
    private javax.swing.JMenuItem menu_transferencias;
    private javax.swing.JPopupMenu popup_jugadores;
    private javax.swing.JSpinner spinner_edad;
    private javax.swing.JSpinner spinner_edadmodificar;
    private javax.swing.JTextField tf_ciudad;
    private javax.swing.JTextField tf_estadio;
    private javax.swing.JTextField tf_nombreJug;
    private javax.swing.JTextField tf_nombre_modificar;
    private javax.swing.JTextField tf_nombreequipos;
    private javax.swing.JTextField tf_pais;
    private javax.swing.JPanel transferencias_goback;
    private javax.swing.JLabel transferencias_gobacktext;
    private javax.swing.JTree tree_equipos;
    // End of variables declaration//GEN-END:variables
}
